import {
  CheckCircle,
  AlertCircle,
  Ship,
  Activity,
  TrendingUp,
  Lock,
} from "lucide-react";
import { QuestData, VerificationGate } from "@/lib/workbench-types";

interface ShipGateViewProps {
  walletBound: boolean;
  ckbRpcOnline: boolean;
  questData: QuestData | null;
  gates: VerificationGate[];
  bossFightSolved: boolean;
  shipped: boolean;
  onShip: () => void;
}

export default function ShipGateView({
  walletBound,
  ckbRpcOnline,
  questData,
  gates,
  bossFightSolved,
  shipped,
  onShip,
}: ShipGateViewProps) {
  const isAllGatesPassed = gates.every((gate) => gate.isCompleted);
  const canShip = Boolean(walletBound && ckbRpcOnline && bossFightSolved && isAllGatesPassed && questData && !shipped);

  return (
    <div className="bg-[#0B0C0E] text-on-surface font-sans p-4 md:p-8 max-w-7xl mx-auto flex flex-col gap-8 min-h-screen">
      <div className="border-b border-glass-border pb-6">
        <h1 className="text-3xl font-extrabold text-white tracking-tight flex items-center gap-3">
          <Ship className="text-electric-blue w-8 h-8" />
          Ship Gate Command
        </h1>
        <p className="text-on-surface-variant text-sm mt-1 max-w-xl">
          Finalize the verified quest envelope after wallet proof, backend readiness, generated-file verification, and boss comprehension all pass.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-[#16181D] border border-glass-border rounded-xl p-6 flex flex-col justify-between h-44">
          <div className="flex justify-between items-start">
            <span className="font-mono text-[10px] text-on-surface-variant uppercase font-bold">
              Reward Claim State
            </span>
            <Lock className="text-warning-amber w-4 h-4" />
          </div>
          <div>
            <span className="text-2xl md:text-3xl font-black text-white font-mono">
              {shipped ? "UNLOCKED" : "LOCKED"}
            </span>
            <span className="text-[10px] font-mono text-on-surface-variant block mt-1">
              {shipped ? "READY FOR CHAIN CLAIM ADAPTER" : "WAITING ON ALL GATES"}
            </span>
          </div>
        </div>

        <div className="bg-[#16181D] border border-glass-border rounded-xl p-6 flex flex-col justify-between h-44">
          <div className="flex justify-between items-start">
            <span className="font-mono text-[10px] text-on-surface-variant uppercase font-bold">
              Proof Envelope
            </span>
            <TrendingUp className="text-cyber-green w-4 h-4" />
          </div>
          <div>
            <span className="text-2xl md:text-3xl font-black text-cyber-green font-mono">
              {questData ? "READY" : "EMPTY"}
            </span>
            <span className="text-[10px] font-mono text-on-surface-variant block mt-1">
              GENERATED BY VIBEQUEST-CORE
            </span>
          </div>
        </div>

        <div className="bg-[#16181D] border border-glass-border rounded-xl p-6 flex flex-col justify-between h-44">
          <div className="flex justify-between items-start">
            <span className="font-mono text-[10px] text-on-surface-variant uppercase font-bold">
              Encounter Level
            </span>
            <Activity className="text-electric-blue w-4 h-4" />
          </div>
          <div>
            <span className="text-2xl md:text-3xl font-black text-white font-mono">
              TIER {questData ? (questData.bossFight.title.length % 3) + 2 : "1"}
            </span>
            <span className="text-[10px] font-mono text-on-surface-variant block mt-1">
              COMPREHENSION RISK RANK
            </span>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        <div className="lg:col-span-7 flex flex-col gap-6">
          <div className="bg-[#16181D] border border-glass-border rounded-xl p-6 flex flex-col gap-5">
            <h2 className="text-lg font-bold text-white tracking-tight">
              Pre-Flight Shipping Verification
            </h2>

            <div className="flex flex-col gap-3">
              <CheckRow
                passed={walletBound}
                title="Identity Proof Token"
                description="CKB secp256k1 wallet proof is bound to this quest session."
              />
              <CheckRow
                passed={ckbRpcOnline}
                title="Backend Readiness"
                description="OpenAI, CKB RPC, and Fiber RPC are ready through vibequest-core."
              />
              <CheckRow
                passed={isAllGatesPassed}
                title="Generated Workspace Checks"
                description="Generated files passed proof, test, and denial-path checks."
              />
              <CheckRow
                passed={bossFightSolved}
                title="Boss Challenge Solution"
                description="The builder proved they understand and can defend the generated diff."
              />
            </div>

            {shipped ? (
              <div className="bg-cyber-green/5 border border-cyber-green/20 p-5 rounded-lg text-center font-mono text-xs text-cyber-green font-bold">
                PROOF ENVELOPE LOCKED. REWARD CLAIM ADAPTER CAN CONSUME THIS STATE.
              </div>
            ) : (
              <button
                onClick={onShip}
                disabled={!canShip}
                className="w-full py-4 bg-cyber-green hover:brightness-110 disabled:brightness-50 disabled:cursor-not-allowed text-[#0B0C0E] font-black text-sm tracking-widest uppercase rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer shadow-[0_0_20px_rgba(0,255,100,0.15)]"
              >
                <Ship className="w-5 h-5 animate-pulse" />
                Lock Proof Envelope
              </button>
            )}
            {!canShip && !shipped && (
              <span className="text-[10px] font-mono text-red-400 text-center block mt-1 leading-tight uppercase">
                Complete every verification gate and solve the active boss encounter to unlock shipping.
              </span>
            )}
          </div>
        </div>

        <div className="lg:col-span-5 flex flex-col gap-6">
          <div className="bg-[#16181D] border border-glass-border rounded-xl p-5 flex flex-col gap-4">
            <h2 className="text-sm font-mono font-bold uppercase tracking-wider text-white border-b border-glass-border pb-3 flex items-center gap-2">
              <Activity className="text-electric-blue w-4 h-4" />
              Active Dispatch Channel
            </h2>

            <div className="relative border border-glass-border bg-[#0B0C0E]/80 rounded-lg p-5 flex flex-col items-center justify-center gap-6 h-64 overflow-hidden text-center select-none">
              <div className="absolute inset-0 z-0 opacity-10 flex items-center justify-center">
                <Ship className="w-48 h-48 text-electric-blue" />
              </div>

              {shipped ? (
                <div className="flex flex-col items-center gap-3 z-10">
                  <div className="w-16 h-16 rounded-full bg-cyber-green/10 flex items-center justify-center border-2 border-cyber-green animate-pulse">
                    <CheckCircle className="text-cyber-green w-8 h-8" />
                  </div>
                  <h3 className="text-white font-bold text-base uppercase">Envelope Locked</h3>
                  <p className="text-xs text-on-surface-variant max-w-xs">
                    The quest result is ready for the next backend reward-claim endpoint.
                  </p>
                </div>
              ) : questData ? (
                <div className="flex flex-col items-center gap-3 z-10">
                  <div className="w-16 h-16 rounded-full bg-warning-amber/10 flex items-center justify-center border border-warning-amber/20 animate-pulse">
                    <AlertCircle className="text-warning-amber w-8 h-8" />
                  </div>
                  <h3 className="text-white font-bold text-base uppercase">Envelope Preloaded</h3>
                  <p className="text-xs text-on-surface-variant max-w-xs">
                    Finish proof checks and boss comprehension to lock the claim envelope.
                  </p>
                </div>
              ) : (
                <div className="flex flex-col items-center gap-3 z-10">
                  <div className="w-16 h-16 rounded-full bg-glass-border flex items-center justify-center border border-dashed border-on-surface-variant/30">
                    <Lock className="text-on-surface-variant w-6 h-6" />
                  </div>
                  <h3 className="text-on-surface-variant font-bold text-base uppercase">Dock Empty</h3>
                  <p className="text-xs text-on-surface-variant max-w-xs">
                    Generate a quest and resolve the workspace gates to prepare shipment.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function CheckRow({
  passed,
  title,
  description,
}: {
  passed: boolean;
  title: string;
  description: string;
}) {
  return (
    <div className="p-4 bg-[#0B0C0E]/60 border border-glass-border rounded-lg flex items-center justify-between gap-4">
      <div className="flex items-center gap-3">
        {passed ? (
          <CheckCircle className="text-cyber-green w-5 h-5 shrink-0" />
        ) : (
          <AlertCircle className="text-red-500 w-5 h-5 shrink-0" />
        )}
        <div>
          <h3 className="font-mono text-xs font-bold text-white uppercase">{title}</h3>
          <p className="text-[11px] text-on-surface-variant">{description}</p>
        </div>
      </div>
      <span className={"font-mono text-[10px] font-bold uppercase " + (passed ? "text-cyber-green" : "text-red-500")}>
        {passed ? "PASSED" : "FAILED"}
      </span>
    </div>
  );
}
